/*
Copyright 2008-2010 Gephi
Authors : Mathieu Bastian <mathieu.bastian@gephi.org>
Website : http://www.gephi.org

This file is part of Gephi.

DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.

Copyright 2011 Gephi Consortium. All rights reserved.

The contents of this file are subject to the terms of either the GNU
General Public License Version 3 only ("GPL") or the Common
Development and Distribution License("CDDL") (collectively, the
"License"). You may not use this file except in compliance with the
License. You can obtain a copy of the License at
http://gephi.org/about/legal/license-notice/
or /cddl-1.0.txt and /gpl-3.0.txt. See the License for the
specific language governing permissions and limitations under the
License.  When distributing the software, include this License Header
Notice in each file and include the License files at
/cddl-1.0.txt and /gpl-3.0.txt. If applicable, add the following below the
License Header, with the fields enclosed by brackets [] replaced by
your own identifying information:
"Portions Copyrighted [year] [name of copyright owner]"

If you wish your version of this file to be governed by only the CDDL
or only the GPL Version 3, indicate your decision by adding
"[Contributor] elects to include this software in this distribution
under the [CDDL or GPL Version 3] license." If you do not indicate a
single choice of license, a recipient has the option to distribute
your version of this file under either the CDDL, the GPL Version 3 or
to extend the choice of license to its licensees as provided above.
However, if you add GPL Version 3 code and therefore, elected the GPL
Version 3 license, then the option applies only if the new code is
made subject to such option by the copyright holder.

Contributor(s):

Portions Copyrighted 2011 Gephi Consortium.
 */
package org.gephi.ui.tinkerpopfilters.plugin.graph;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.gephi.tinkerpopfilters.plugin.graph.VertexOrientedBuilder.VertexOrientedFilter;

/**
 *
 * @author Xia Zhu
 */
public class VertexOrientedPanel extends javax.swing.JPanel {

    private VertexOrientedFilter vertexFilter;

    /** Creates new form VertexOrientedPanel */
    public VertexOrientedPanel() {

        initComponents();

        gremlinScriptTextField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                vertexFilter.getProperties()[0].setValue(gremlinScriptTextField.getText());
            }
        });

        gremlinScriptTextField.getDocument().addDocumentListener(new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                vertexFilter.getProperties()[0].setValue(gremlinScriptTextField.getText());
            }
            public void removeUpdate(DocumentEvent e) {
                vertexFilter.getProperties()[0].setValue(gremlinScriptTextField.getText());
            }
            public void insertUpdate(DocumentEvent e) {
                vertexFilter.getProperties()[0].setValue(gremlinScriptTextField.getText());
            }
        });

        withSubgraphCheckbox.addItemListener(new ItemListener() {

            public void itemStateChanged(ItemEvent e) {
                if (!vertexFilter.isWithSubgraph() == withSubgraphCheckbox.isSelected()) {
                    vertexFilter.getProperties()[1].setValue(withSubgraphCheckbox.isSelected());
                }
            }
        });

        newImportCheckbox.addItemListener(new ItemListener() {

            public void itemStateChanged(ItemEvent e) {
                if (!vertexFilter.isNewImport() == newImportCheckbox.isSelected()) {
                    vertexFilter.getProperties()[2].setValue(newImportCheckbox.isSelected());
                }
            }
        });
    }

    public void setup(VertexOrientedFilter vertexFilter) {
        this.vertexFilter = vertexFilter;
        gremlinScriptTextField.setText(vertexFilter.getGremlinScript());
        withSubgraphCheckbox.setSelected(vertexFilter.isWithSubgraph());
        newImportCheckbox.setSelected(vertexFilter.isNewImport());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelGremlinScript = new javax.swing.JLabel();
        gremlinScriptTextField = new javax.swing.JTextField();
        withSubgraphCheckbox = new javax.swing.JCheckBox();
        newImportCheckbox = new javax.swing.JCheckBox();

        labelGremlinScript.setText(org.openide.util.NbBundle.getMessage(VertexOrientedPanel.class, "VertexOrientedPanel.labelGremlinScript.text")); // NOI18N

        gremlinScriptTextField.setText(org.openide.util.NbBundle.getMessage(VertexOrientedPanel.class, "VertexOrientedPanel.gremlinScriptTextField.text")); // NOI18N
        gremlinScriptTextField.setToolTipText(org.openide.util.NbBundle.getMessage(VertexOrientedPanel.class, "VertexOrientedPanel.gremlinScriptTextField.toolTipText")); // NOI18N

        withSubgraphCheckbox.setText(org.openide.util.NbBundle.getMessage(VertexOrientedPanel.class, "VertexOrientedPanel.withSubgraphCheckbox.text")); // NOI18N
        newImportCheckbox.setText(org.openide.util.NbBundle.getMessage(VertexOrientedPanel.class, "VertexOrientedPanel.newImportCheckbox.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelGremlinScript))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withSubgraphCheckbox)
                    .addComponent(newImportCheckbox)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(gremlinScriptTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        ))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelGremlinScript)
                    .addComponent(gremlinScriptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    )
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(withSubgraphCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newImportCheckbox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelGremlinScript;
    private javax.swing.JTextField gremlinScriptTextField;
    private javax.swing.JCheckBox withSubgraphCheckbox;
    private javax.swing.JCheckBox newImportCheckbox;
    // End of variables declaration//GEN-END:variables
}
